BATCH_SIZE = 64
EPOCHS = 10
MIN_DELTA = 1e-3
PATIENCE = 3

INPUT_IMAGE_WIDTH = 360
INPUT_IMAGE_HEIGHT = 240
INPUT_IMAGE_CHANNELS = 3
INPUT_IMAGE_CROP_VERTICAL_PIXELS = 0

WEIGHT_ANGLE_LOSS = 0.5
WEIGHT_THROTTLE_LOSS = 0.5